### ISSUE TITLE
Wallet Page with balances

### ISSUE THREAD

**Issue by antonpegov** [zeropoolnetwork/zeropool-frontend#27]
**As a User**
**I want to** open wallet page
**so that** I could se my balances

### **Acceptance Criteria**:

**Given** An existed User accessing ZP Wallet App
**When** navigating the main page
- [x] I can see wallet name, "Main Wallet" by default
- [x] I can see total balance (hardcode it for now)
- [x] I can see list of balances with name and amount

**When** I click on the row
- [x] I redirecting to token screen
- [x] I can see token balance
- [ ] I can see transction history
- [x] I can see Send/Recive/CopyAddress buttons (disabled for now)
