### ISSUE TITLE
Send Tokens

### ISSUE THREAD

**Issue by antonpegov** [zeropoolnetwork/zeropool-frontend#36]
**As a User**
**I want to** open Send page
**so that** I could enter transaction details

### **Acceptance Criteria**:

**Given** An existed User accessing ZP Wallet App
**When** navigating the Send page
- [x] I can see title with token symbol
- [x] I can see address input with past button
- [x] I can see token amount input with 'max' button 
- [x] I can see 'next' button disabled if some input is invalid  

**When** I click on the 'past' button
- [x] I can see value from the clipboard copyed in the address input
- [x] I can see input not changed if clipboard contain invalid data
- [x] I can see confirmation snack on success
- [x] I can see warning snack on fail

**When** I entering address
- [x] I can see indication when addres is invalid
- [x] I can see indication when addres is valid
- [x] I can see indication when addres is private

**When** I entering address
- [x] I can see indication when amount is invalid
- [x] I can see indication when amount is valid
- [x] I can press 'next' button when all data valid
