### ISSUE TITLE
New wallet generation

### ISSUE THREAD

**Issue by antonpegov** [zeropoolnetwork/zeropool-frontend#5]
**As a User**
**I want to** create a New Wallet
**so that** I could access it

### **Acceptance Criteria**:

**Given** A new User accessing Welcome Screen
**When** pressing "Create a New Wallet"
- [ ] I get to seed phrase generation screen
- [ ] I confirm secret phrase stroring by pressing SUBMIT button
- [ ] I can enter a secret phrase for verification
- [ ] I can press an activated CONFIRM button
- [ ] I can set up a password and REGISTER

**Given** I enter a wrong secret phrase
- [ ] I see an alert message "The phrases do not match!"
- [ ] CONFIRM button being disabled
- [ ] I can make a new attempt

**Given** I enter bad password or wrong password confirmation
- [ ] I can't REGISTER 
- [ ] I can see help messages
