### ISSUE TITLE
Bug fixes

### ISSUE THREAD

**Issue by antonpegov** [zeropoolnetwork/zeropool-frontend#82]
- [x]  fix typos in the readmy
- [x]  fix ethereum non-private transaction
- [x]  fix randomly wrong address asigning when adding new wallets
- [x]  fix when clicking back mouse button on Receive page, some times BACK action firing two times
- [ ]  fix tooltip apsent when hower on extended wallet row (amount subrow) 
- [ ]  fix SendConfirmation component: spiner insted of button
- [ ]  fix bug when not able to return back from transactions log after sending transaction
- [ ]  fix app crash on http errors
- [ ]  fix all balanses request crached if one of the networks is unavailable
- [ ]  fix app lagging while connecting to the api library
- [ ]  fix total balance not updating after adding new wallet
- [ ]  [POSTPONE] fix non-ethereum non-private transactions
